baseURL = "https://thekennethlove.com/"
languageCode = "en-us"
title = "Kenneth Love"
theme = "editor"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."
rssLimit = 10
enableRobotsTXT = true
pygmentsCodefences = true
pygmentsUseClasses = true
sectionPagesMenu = "pagesMenu"

[author]
    name = "Kenneth Love"

[permalinks]
    posts = "/:year/:month/:title/"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[[menu.main]]
    name = "README.md"
    identifier = "readme"
    url = "/"
    weight = 100
[[menu.main]]
    name = "social.md"
    identifier = "social"
    url = "/social/"
    weight = 110
[[menu.main]]
    name = "videos.md"
    identifier = "videos"
    url = "/videos/"
    weight = 120
[[menu.main]]
    name = "posts/"
    identifier = "posts"
    url = "/posts/"
    weight = 130